logging:
  level:
    com.nexusfi.server: info

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    com.nexusfi.server: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    p6spy: info

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.nexusfi.server: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    p6spy: info

---
spring:
  config:
    activate:
      on-profile: prd
decorator:
  datasource:
    p6spy:
      enable-logging: false
logging:
  level:
    com.nexusfi.server: info