# P6Spy 및 데이터소스 관련 데코레이터 설정 (Logback 설정과는 별개)
decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j

---
spring:
  config:
    activate:
      on-profile: prd
decorator:
  datasource:
    p6spy:
      # 운영 환경에서는 p6spy Log 비활성화
      enable-logging: false
