spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 20215482618-vv77f6f2jrgkgrjutdqe331ek28qbeuh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: 0199bd6766ecdb931c2f0ee387b06ed7
            client-secret: HRVhM2f4PxOPuYDMQkxcPHqQrneytzdL
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              # account_email 제거됨 (권한 없음)
            client-name: Kakao
        
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id